service: lighthouse-as-a-service
app: lighthouse-as-a-service
org: jakepartusch

provider:
  name: aws
  runtime: nodejs8.10

functions:
  evaluate:
    handler: src/handler.evaluate
    timeout: 180
    events:
      - http:
          path: evaluate
          method: get
